### ISSUE TITLE
How do you generate the saliency gt?

### ISSUE THREAD

**Issue by ProNoobLi** [juanjo3ns/SalBCE#1]
Hi, nice work

I am trying to use your Datasets of LEDOV, but neither of your code and original LEDOV code provides the detailed generation of gt_saliency_map. Could you please explain how could I make such map using the fixation data(groups of pixel coordinates in LEDOV dataset)?

**Comment by juanjo3ns** [comment]
If I remember correctly I modified a matlab code they provide in order to generate the ground truth. You can find it [here](https://github.com/juanjo3ns/SalBCE/blob/master/src/salgan_ledov/generate_gt.m). But better check their original script first.
