### ISSUE TITLE
Function not found

### ISSUE THREAD

**Issue by ProNoobLi** [juanjo3ns/SalBCE#2]
Hi, nice work

I am trying to use your Datasets of LEDOV, but neither of your code and original LEDOV code provides the detailed generation of gt_saliency_map. Could you please explain how could I make such map using the fixation data(groups of pixel coordinates in LEDOV dataset)?

------
I found the generate_gt.m but one function is not included in this repo
https://github.com/juanjo3ns/SalBCE/blob/ac52af743b94961cdb44c5d89774b72fc8acfd3e/src/salgan_ledov/generate_gt.m#L108

**Comment by juanjo3ns** [comment]
#1 Already solved here
